package audit

import (
	"sort"

	"github.com/tolvi-labs/canary/internal/manifest"
)

// UntestedRange is one instrumented source-code block with zero covering
// tests anywhere in the manifest — Forge's to-do list, never
// auto-generated by Canary.
type UntestedRange struct {
	File               string
	StartLine, EndLine int
}

// Result is the outcome of one audit pass over a GlobalManifest.
type Result struct {
	OrphanTests   []string
	UntestedPaths []UntestedRange
}

// Compute finds orphan tests (a registered test that never showed
// Count > 0 for any block anywhere) and untested paths (a covered range
// with zero covering tests).
func Compute(m manifest.GlobalManifest) Result {
	coveredBy := map[string]bool{}
	var untested []UntestedRange
	for file, ranges := range m.Coverage {
		for _, r := range ranges {
			if len(r.Tests) == 0 {
				untested = append(untested, UntestedRange{File: file, StartLine: r.StartLine, EndLine: r.EndLine})
				continue
			}
			for _, t := range r.Tests {
				coveredBy[t] = true
			}
		}
	}
	sort.Slice(untested, func(i, j int) bool {
		if untested[i].File != untested[j].File {
			return untested[i].File < untested[j].File
		}
		return untested[i].StartLine < untested[j].StartLine
	})

	var orphans []string
	for _, t := range m.Tests {
		if !coveredBy[t] {
			orphans = append(orphans, t)
		}
	}
	sort.Strings(orphans)

	return Result{OrphanTests: orphans, UntestedPaths: untested}
}
